library(Matrix)
a <- matrix(c(4,1,1,3),2)
b <- c(1,2)
x <- solve(a,b)
stopifnot(max(abs(a %*% x-b)) < 1e-12)
stopifnot(max(abs(solve(Matrix(a,sparse=TRUE),b)-x)) < 1e-12)
diagonal <- Diagonal(x=1:20)
e <- RSpectra::eigs_sym(as(as(diagonal,'generalMatrix'),'CsparseMatrix'),k=2)$values
stopifnot(max(abs(sort(e)-c(19,20))) < 1e-10)
stopifnot(max(abs(expm::expm(diag(c(1,2)))-diag(exp(c(1,2))))) < 1e-12)
stopifnot(max(abs(pracma::pinv(a) %*% b-x)) < 1e-12)
cat('R dense/sparse solve, partial eigenvalues, matrix exponential and pseudoinverse passed\n')
for (p in c('Matrix','RcppEigen','RcppArmadillo','RSpectra','expm','pracma'))
    cat(p,as.character(packageVersion(p)),'\n')
